apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: one-data-studio
spec:
  replicas: 6
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: one-data-studio
spec:
  minReplicas: 6
  maxReplicas: 50
